version: '3.9'


services:
  db:
    restart: always
    image: postgres:16.3-alpine
    container_name: service-db
    env_file:
      - .env
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  back:
    restart: always
    build: ./
    container_name: backend_remote_service
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8010"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/media
    ports:
      - "8010:8010"
    depends_on:
      - db

  redis:
    image: redis
    container_name: redis_remote_service

  celery:
    restart: always
    build: ./
    container_name: celery_remote_service
    command: sh -c "celery -A remote_service worker --loglevel=info"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/media
    depends_on:
      - redis
      - db

  beat:
    restart: always
    build: ./
    container_name: beat_remote_service
    command: sh -c "celery -A remote_service beat --loglevel=info"
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./static_volume:/app/staticfiles
      - ./media_volume:/app/media
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  static_volume:
  media_volume:
