# Generated by Django 4.2.16 on 2025-02-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB')], default='USD', max_length=3)),
                ('comparison_currency', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB')], default='RUB', max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
